// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFpmf1pyzJa2rOeas_3PFrPwxbraccXkY',
    appId: '1:1000643173864:web:2c056f9c5e99186181d85d',
    messagingSenderId: '1000643173864',
    projectId: 'chatapp-729ce',
    authDomain: 'chatapp-729ce.firebaseapp.com',
    storageBucket: 'chatapp-729ce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmIClYUuRz9mh_skbIOqjz8bWPLClXhSI',
    appId: '1:1000643173864:android:988d00042d5a272581d85d',
    messagingSenderId: '1000643173864',
    projectId: 'chatapp-729ce',
    storageBucket: 'chatapp-729ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7G5b6dSc0oZYTMKmW2FZ_e5hEneXH4zI',
    appId: '1:1000643173864:ios:f47aa4cee39aacf581d85d',
    messagingSenderId: '1000643173864',
    projectId: 'chatapp-729ce',
    storageBucket: 'chatapp-729ce.appspot.com',
    androidClientId: '1000643173864-e7los0sbtfuaq1ja3q651tqjek8gv6ls.apps.googleusercontent.com',
    iosClientId: '1000643173864-krfptu31u7lgr2p2sr1sdlbpn3g1bgjo.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7G5b6dSc0oZYTMKmW2FZ_e5hEneXH4zI',
    appId: '1:1000643173864:ios:f47aa4cee39aacf581d85d',
    messagingSenderId: '1000643173864',
    projectId: 'chatapp-729ce',
    storageBucket: 'chatapp-729ce.appspot.com',
    androidClientId: '1000643173864-e7los0sbtfuaq1ja3q651tqjek8gv6ls.apps.googleusercontent.com',
    iosClientId: '1000643173864-krfptu31u7lgr2p2sr1sdlbpn3g1bgjo.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
